### ISSUE TITLE
Make an option to repeat last movement with a single key

### ISSUE THREAD

**Issue by irigone** [alphapapa/mosey.el#2]
For example, by default Emacs has C-x C-= bound to "text-scale-adjust". After typing C-x C-= the user can type +,=,-,0 to adjust the size of the font, without having to C-x C-= every time.
Now imagine another situation: with mosey, the user configured M-d to kill-word and kill-line. If the user wanted to kill-word several times, he would type M-d and then press d to repeat kill-word. If the user wanted to kill-line, he would M-d M-d and then press d to repeat it.

**Comment by alphapapa** [comment]
Please see one of my other packages, `defrepeater`.

**Comment by irigone** [comment]
Thx
